apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-preview
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
      targetPort: 8080