---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  template:
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
