apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: shippingservice
      previewService: shippingservice-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: shippingservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: 4.193.154.62/sample-microservice/shippingservice:latest
          ports:
            - containerPort: 50051
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
        - name: harbor-pull-secret