apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkoutservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thuanthentran/gitops-for-microservices-demo
    targetRevision: main
    path: checkoutservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true