---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: adservice
      previewService: adservice-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: 4.193.154.62/sample-microservice/adservice:latest
          ports:
          - containerPort: 9555
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          env:
          - name: PORT
            value: "9555"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
      imagePullSecrets:
      - name: harbor-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    protocol: TCP
    targetPort: 9555
    service: ''
---
apiVersion: v1
kind: Service
metadata:
  name: adservice-preview
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    protocol: TCP
    targetPort: 9555
    service: ''
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
