apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # NGUỒN 1: Helm Chart chính thức (Phần "Xác")
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 58.0.0
      helm:
        # Trỏ đến file values.yaml nằm trong Nguồn 2 bên dưới
        valueFiles:
          - $my-configs/monitoring/values.yaml

    # NGUỒN 2: Repo Git của bạn (Phần "Hồn" và các cấu hình bổ sung)
    - repoURL: https://github.com/thuanthentran/gitops-for-microservices-demo
      targetRevision: HEAD
      ref: my-configs # Định danh nguồn này là 'my-configs'
      # Path này chứa file ServiceMonitor để monitor ArgoCD Notifications
      path: monitoring/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Bắt buộc có để cài đặt CRD mượt mà
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
