# FILE NÀY NẰM TRÊN GITHUB CỦA BẠN
prometheus:
  enabled: true
  prometheusSpec:
    retention: 3d
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true
  adminPassword: admin123
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi
  service:
    type: NodePort
    nodePort: 32000
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Manual
          type: prometheus
          url: http://prometheus-operated.monitoring.svc:9090
          isDefault: false
        - name: Loki
          type: loki
          url: http://loki.logging:3100
          isDefault: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi