apiVersion: v1
kind: Service
metadata:
  name: paymentservice-preview
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051