apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/thuanthentran/gitops-for-microservices-demo
    path: kyverno/policies 
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno