apiVersion: v1
kind: Service
metadata:
  name: currencyservice-preview
  labels:
    app: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000
      protocol: TCP
      targetPort: 7000